name: Auto Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'docs/**'
      - '.vscode/**'
      - '*.md'

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  check-changes:
    name: Check for Release-Worthy Changes
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.check.outputs.should-release }}
      release-type: ${{ steps.check.outputs.release-type }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install analysis dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y jq

    - name: Check for protocol changes (Enhanced Analysis)
      id: check
      run: |
        # Get the latest tag (most recent release)
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        
        if [ -z "$LATEST_TAG" ]; then
          echo "No previous release found, creating initial release"
          echo "should-release=true" >> $GITHUB_OUTPUT
          echo "release-type=minor" >> $GITHUB_OUTPUT
          echo "analysis-result={\"version_bump\":\"minor\",\"reason\":\"initial_release\"}" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "Analyzing protocol changes since $LATEST_TAG using enhanced detection"
        
        # Use enhanced proto change analysis
        chmod +x scripts/analyze-proto-changes.sh
        ANALYSIS_RESULT=$(./scripts/analyze-proto-changes.sh "$LATEST_TAG" HEAD)
        
        echo "Analysis result: $ANALYSIS_RESULT"
        
        # Extract version bump recommendation
        VERSION_BUMP=$(echo "$ANALYSIS_RESULT" | jq -r '.version_bump')
        REASON=$(echo "$ANALYSIS_RESULT" | jq -r '.reason')
        BREAKING_COUNT=$(echo "$ANALYSIS_RESULT" | jq -r '.breaking_changes')
        NEW_FEATURES=$(echo "$ANALYSIS_RESULT" | jq -r '.new_features')
        
        echo "Recommended version bump: $VERSION_BUMP ($REASON)"
        echo "Breaking changes detected: $BREAKING_COUNT"
        echo "New features detected: $NEW_FEATURES"
        
        # Also check for non-proto changes that might warrant a release
        BUILD_CHANGES=$(git diff $LATEST_TAG..HEAD --name-only | grep -E '(generate\.sh|Makefile|buf\.yaml|go\.mod|package\.json|\.github/)$' | wc -l)
        BINDING_CHANGES=$(git diff $LATEST_TAG..HEAD --name-only | grep -E 'go/.*\.pb\.go$' | wc -l)
        
        echo "Build/workflow changes: $BUILD_CHANGES"
        echo "Generated binding changes: $BINDING_CHANGES"
        
        # Determine final release decision
        if [ "$VERSION_BUMP" != "none" ]; then
          echo "should-release=true" >> $GITHUB_OUTPUT
          echo "release-type=$VERSION_BUMP" >> $GITHUB_OUTPUT
        elif [ "$BUILD_CHANGES" -gt 0 ] || [ "$BINDING_CHANGES" -gt 0 ]; then
          echo "should-release=true" >> $GITHUB_OUTPUT
          echo "release-type=patch" >> $GITHUB_OUTPUT
          # Update analysis result for patch release
          ANALYSIS_RESULT=$(echo "$ANALYSIS_RESULT" | jq '.version_bump = "patch" | .reason = "build_or_binding_changes"')
        else
          echo "No significant changes detected, skipping release"
          echo "should-release=false" >> $GITHUB_OUTPUT
        fi
        
        # Store detailed analysis for later use
        echo "analysis-result=$ANALYSIS_RESULT" >> $GITHUB_OUTPUT

  auto-release:
    name: Create Automated Release
    needs: check-changes
    if: needs.check-changes.outputs.should-release == 'true'
    uses: loqalabs/.github/.github/workflows/release-create-release.yml@main
    with:
      release-type: ${{ needs.check-changes.outputs.release-type }}
      pre-release: false
      draft: false
      changelog-file: 'CHANGELOG.md'
    secrets: inherit

  update-consumers:
    name: Notify Consumer Services
    needs: [check-changes, auto-release]
    if: needs.check-changes.outputs.should-release == 'true'
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        repo: ['loqa-hub', 'loqa-relay', 'loqa-skills']
        
    steps:
    - name: Create update issue in consumer service
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const repo = '${{ matrix.repo }}';
          const newVersion = '${{ needs.auto-release.outputs.release-version }}';
          const releaseType = '${{ needs.check-changes.outputs.release-type }}';
          
          const title = `Update loqa-proto to ${newVersion}`;
          const body = `
          ## Protocol Update Available
          
          A new ${releaseType} release of \`loqa-proto\` is available: **${newVersion}**
          
          ### Changes
          - View the full changelog: [Release ${newVersion}](https://github.com/loqalabs/loqa-proto/releases/tag/${newVersion})
          
          ### Action Required
          Please update your \`go.mod\`:
          \`\`\`bash
          go get github.com/loqalabs/loqa-proto/go@${newVersion}
          go mod tidy
          \`\`\`
          
          ### Testing
          - [ ] Run \`make quality-check\` 
          - [ ] Run integration tests
          - [ ] Verify protocol compatibility
          
          ---
          *This issue was automatically created by the protocol release workflow.*
          `;
          
          // Check if similar issue already exists
          const existingIssues = await github.rest.issues.listForRepo({
            owner: 'loqalabs',
            repo: repo,
            state: 'open',
            labels: 'protocol-update'
          });
          
          const existingIssue = existingIssues.data.find(issue => 
            issue.title.includes(`Update loqa-proto to ${newVersion}`)
          );
          
          if (!existingIssue) {
            await github.rest.issues.create({
              owner: 'loqalabs',
              repo: repo,
              title: title,
              body: body,
              labels: ['protocol-update', 'dependencies', 'automated']
            });
          }