name: Protocol Buffer CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  generate-bindings:
    name: Generate Protocol Buffer Bindings
    uses: loqalabs/.github/.github/workflows/proto/generate-bindings.yml@main
    with:
      protoc-version: '29.3'
      go-version: '1.23.0'
      python-version: '3.11'
      node-version: '20'
      languages: 'go,python,javascript'
      proto-files: 'audio.proto'
      generate-script: './generate.sh'

  security:
    name: Security Analysis
    uses: loqalabs/.github/.github/workflows/security-scan.yml@main
    with:
      language: 'go'
      go-version: '1.23.0'

  package-release:
    name: Package Release Assets
    runs-on: ubuntu-latest
    needs: [generate-bindings, security]
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Download all binding artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./bindings

    - name: Package release assets
      run: |
        mkdir -p release-assets
        
        # Package Go bindings
        if [[ -d "bindings/go-bindings" ]]; then
          tar -czf release-assets/go-bindings-${{ github.ref_name }}.tar.gz -C bindings go-bindings
        fi
        
        # Package Python bindings
        if [[ -d "bindings/python-bindings" ]]; then
          tar -czf release-assets/python-bindings-${{ github.ref_name }}.tar.gz -C bindings python-bindings
        fi
        
        # Package JavaScript bindings
        if [[ -d "bindings/javascript-bindings" ]]; then
          tar -czf release-assets/javascript-bindings-${{ github.ref_name }}.tar.gz -C bindings javascript-bindings
        fi
        
        ls -la release-assets/

    - name: Upload release assets
      uses: actions/upload-artifact@v4
      with:
        name: release-assets
        path: release-assets/

    - name: Attach to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release-assets/*