name: Protocol Buffer CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]

jobs:
  validate:
    name: Validate Protocol Buffers
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Protocol Buffer Compiler
      uses: arduino/setup-protoc@v2
      with:
        version: '29.3'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Print protoc version
      run: protoc --version

    - name: Validate proto files
      run: |
        protoc --descriptor_set_out=/dev/null audio.proto

  generate-go:
    name: Generate Go Bindings
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'

    - name: Verify Go version
      run: go version

    - name: Cache Go modules and build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Protocol Buffer Compiler
      uses: arduino/setup-protoc@v2
      with:
        version: '29.3'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Print protoc version
      run: protoc --version

    - name: Install protoc-gen-go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

    - name: Generate Go bindings
      run: |
        ./generate.sh

    - name: Check for differences
      run: |
        git diff --exit-code go/ || (
          echo "::error::Go bindings are out of date. Please run ./generate.sh and commit the result."
          exit 1
        )

    - name: Test Go module
      run: |
        cd go
        go mod tidy
        go test ./...

    - name: Upload Go bindings
      uses: actions/upload-artifact@v4
      with:
        name: go-bindings
        path: go/

  generate-other:
    name: Generate Other Language Bindings
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Protocol Buffer Compiler
      uses: arduino/setup-protoc@v2
      with:
        version: '29.3'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python protobuf
      run: |
        pip install grpcio-tools

    - name: Generate Python bindings
      run: |
        mkdir -p python
        python -m grpc_tools.protoc \
          --proto_path=. \
          --python_out=python/ \
          --grpc_python_out=python/ \
          audio.proto

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Cache Go modules and build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Generate JavaScript bindings
      run: |
        npm install -g grpc-tools
        mkdir -p javascript
        grpc_tools_node_protoc \
          --proto_path=. \
          --js_out=import_style=commonjs,binary:javascript/ \
          --grpc_out=grpc_js:javascript/ \
          audio.proto

    - name: Upload language bindings
      uses: actions/upload-artifact@v4
      with:
        name: multi-language-bindings
        path: |
          python/
          javascript/

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
  publish-bindings:
    name: Publish Go Bindings to bindings/go branch
    runs-on: ubuntu-latest
    needs: generate-go
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Switch to bindings/go branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin bindings/go || true
          git checkout -B bindings/go origin/bindings/go || git checkout -b bindings/go

      - name: Overwrite with go/ contents
        run: |
          git rm -rf . --ignore-unmatch
          cp -r go/. .
          git add .
          git commit -m "Update Go bindings from main" || echo "No changes to commit"

      - name: Force push to bindings/go branch
        run: |
          git push origin bindings/go --force