name: Proto Validation

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '*.proto'
      - 'generate.sh'
      - 'Makefile'
      - 'buf.yaml'
      - '.github/workflows/proto-validation.yml'
  push:
    branches: [ main ]
    paths:
      - '*.proto'
      - 'generate.sh' 
      - 'Makefile'
      - 'buf.yaml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  proto-validation:
    name: Validate Protocol Buffers
    uses: loqalabs/.github/.github/workflows/proto-generate-bindings.yml@main
    with:
      protoc-version: '29.3'
      go-version: '1.25.1'
      python-version: '3.11'
      node-version: '20'
      languages: 'go,python,javascript'
      proto-files: 'audio.proto'
      generate-script: './generate.sh'

  breaking-change-detection:
    name: Breaking Change Detection
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout base branch
      uses: actions/checkout@v5
      with:
        ref: ${{ github.base_ref }}
        path: base
        
    - name: Checkout PR branch
      uses: actions/checkout@v5
      with:
        ref: ${{ github.head_ref }}
        path: pr
        
    - name: Install buf
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Check for breaking changes
      id: breaking_check
      continue-on-error: true
      run: |
        cd pr
        
        # Use buf to check for breaking changes against the base branch
        buf breaking --against ../base || {
          echo "breaking_changes_detected=true" >> $GITHUB_OUTPUT
          echo "Breaking changes detected!"
          exit 1
        }
        
        echo "breaking_changes_detected=false" >> $GITHUB_OUTPUT
        echo "No breaking changes detected."
        
    - name: Comment on PR if breaking changes detected
      if: steps.breaking_check.outputs.breaking_changes_detected == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const message = `
          ## ⚠️ Breaking Changes Detected
          
          This PR contains breaking changes to the protocol buffer definitions. 
          
          ### Impact
          Breaking changes require coordinated updates across all consuming services:
          - \`loqa-hub\`
          - \`loqa-relay\` 
          - \`loqa-skills\`
          
          ### Required Actions
          1. **Coordinate with service teams** before merging
          2. **Create feature branches** in ALL affected services
          3. **Test cross-service compatibility** using development mode
          4. **Update consuming services** in dependency order
          5. **Plan coordinated deployment** to avoid service disruption
          
          ### Development Mode Testing
          Use development mode to test changes before releasing:
          \`\`\`bash
          # Enable development mode for testing
          cd ../
          ./loqa/tools/proto-dev-mode.sh dev
          
          # Test changes across services
          cd loqa-hub && make quality-check
          cd ../loqa-relay && make test
          
          # Switch back to production mode when done
          ./loqa/tools/proto-dev-mode.sh prod
          \`\`\`
          
          ---
          *This comment was automatically generated by the proto validation workflow.*
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });

# Note: Consumer compatibility testing removed during workflow cleanup
# This functionality can be re-enabled when consumer repositories become accessible
# For manual testing, use the development mode approach described in PHASE2_AUTOMATION.md