name: Security Scan

on:
  schedule:
    # Weekly security scan on Sundays at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

permissions:
  contents: read
  security-events: write

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.1'
        
    - name: Run gosec Security Scanner
      uses: securecodewarrior/github-action-gosec@master
      with:
        args: './go/...'
        
    - name: Run govulncheck
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        cd go
        govulncheck ./...