name: Security Scan

on:
  schedule:
    # Weekly security scan on Sundays at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  security:
    name: Security Analysis
    uses: loqalabs/.github/.github/workflows/security-scan.yml@main
    with:
      language: 'go'
      go-version: '1.25.1'
      working-directory: 'go'
    secrets: inherit