name: Test Protocol Generation

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  test-protocol-generation:
    name: Test Protocol Generation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.1'
        
    - name: Install Protocol Buffer Compiler
      run: |
        # Install protoc
        PROTOC_VERSION="29.3"
        curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip"
        sudo unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local bin/protoc
        sudo unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local 'include/*'
        rm -f protoc-${PROTOC_VERSION}-linux-x86_64.zip
        
        # Install Go protoc plugins
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        
        # Verify installation
        protoc --version
        
    - name: Test protocol generation
      run: |
        echo "Testing protocol buffer generation..."
        ./generate.sh
        
        echo "Verifying generated files exist..."
        if [ ! -f "go/audio/audio.pb.go" ]; then
          echo "❌ Go protobuf files not generated"
          exit 1
        fi
        
        if [ ! -f "go/audio/audio_grpc.pb.go" ]; then
          echo "❌ Go gRPC files not generated"
          exit 1
        fi
        
        echo "✅ Protocol generation successful"
        
    - name: Test Go module compilation
      run: |
        cd go
        go mod tidy
        go build ./...
        echo "✅ Go bindings compile successfully"